통계학 교과서 

In [1]:
#통계 처리와 scipy
import numpy as np 
import scipy as sp
%precision 3 #표시되는 소수점 이하 자릿수가 3

'%.3f'

In [2]:
#데이터가 1가지 종류밖에 없을 경우 1변량 데이터 
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [4]:
#합계와 샘플사이즈 
import scipy as sp
sp.sum(fish_data)

/var/folders/x4/rh_l0vln5g9bf9fqbtvsc7m80000gn/T/ipykernel_1666/1277425378.py:3: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  sp.sum(fish_data)


40

In [5]:
len(fish_data)

10

In [6]:
#평균값(기댓값)
N = len(fish_data)
sum_value = sp.sum(fish_data)
mu = sum_value/N
mu

/var/folders/x4/rh_l0vln5g9bf9fqbtvsc7m80000gn/T/ipykernel_1666/887298739.py:3: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  sum_value = sp.sum(fish_data)


4.000

In [7]:
sp.mean(fish_data)

/var/folders/x4/rh_l0vln5g9bf9fqbtvsc7m80000gn/T/ipykernel_1666/438933225.py:1: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  sp.mean(fish_data)


4.000

In [9]:
#표본분산 - 데이터가 평균값에서 얼마나 떨어져 있는지 나타내는 지표 
#(실제값-평균)**2 / N
sigma_2_sample = sp.sum((fish_data - mu)**2)/N
sigma_2_sample

/var/folders/x4/rh_l0vln5g9bf9fqbtvsc7m80000gn/T/ipykernel_1666/2399646263.py:3: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  sigma_2_sample = sp.sum((fish_data - mu)**2)/N


1.200

In [10]:
sp.var(fish_data, ddof=0) #ddof:자유도보정. 분산이나 표준편차 계산할 때 분모에서 얼마나 빼줄지

/var/folders/x4/rh_l0vln5g9bf9fqbtvsc7m80000gn/T/ipykernel_1666/2817611044.py:1: DeprecationWarning: scipy.var is deprecated and will be removed in SciPy 2.0.0, use numpy.var instead
  sp.var(fish_data, ddof=0) #ddof:자유도보정. 분산이나 표준편차 계산할 때 분모에서 얼마나 빼줄지


1.200

In [16]:
#불편분산 : 표본분산은 분산을 과소추정하는 경향이 있기에 이 경향을 없애기 위한 것
sigma_2 =sp.sum((fish_data-mu)**2/(N-1))
sigma_2

/var/folders/x4/rh_l0vln5g9bf9fqbtvsc7m80000gn/T/ipykernel_1666/2977263113.py:2: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  sigma_2 =sp.sum((fish_data-mu)**2/(N-1))


1.333

In [17]:
sp.var(fish_data, ddof=1)

/var/folders/x4/rh_l0vln5g9bf9fqbtvsc7m80000gn/T/ipykernel_1666/2102350481.py:1: DeprecationWarning: scipy.var is deprecated and will be removed in SciPy 2.0.0, use numpy.var instead
  sp.var(fish_data, ddof=1)


1.333

In [18]:
#표준편차
sigma = sp.sqrt(sigma_2)
sigma

/var/folders/x4/rh_l0vln5g9bf9fqbtvsc7m80000gn/T/ipykernel_1666/3190209917.py:2: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  sigma = sp.sqrt(sigma_2)


1.155

In [19]:
sp.std(fish_data, ddof=1)

/var/folders/x4/rh_l0vln5g9bf9fqbtvsc7m80000gn/T/ipykernel_1666/3259494718.py:1: DeprecationWarning: scipy.std is deprecated and will be removed in SciPy 2.0.0, use numpy.std instead
  sp.std(fish_data, ddof=1)


1.155

In [20]:
#표준화
#데이터 평균을 0으로, 표준편차(분산)를 1로 하는 변환
fish_data - mu

array([-2., -1., -1.,  0.,  0.,  0.,  0.,  1.,  1.,  2.])

In [21]:
sp.mean(fish_data-mu)

/var/folders/x4/rh_l0vln5g9bf9fqbtvsc7m80000gn/T/ipykernel_1666/1995335114.py:1: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  sp.mean(fish_data-mu)


0.000

In [22]:
#데이터의 표준편차(분산)를 1로 만드는 방법-> 데이터를 일률적으로 표준편차로 나누는 것
fish_data/sigma

array([1.732, 2.598, 2.598, 3.464, 3.464, 3.464, 3.464, 4.33 , 4.33 ,
       5.196])

In [23]:
sp.std(fish_data/sigma, ddof=1)

/var/folders/x4/rh_l0vln5g9bf9fqbtvsc7m80000gn/T/ipykernel_1666/160741353.py:1: DeprecationWarning: scipy.std is deprecated and will be removed in SciPy 2.0.0, use numpy.std instead
  sp.std(fish_data/sigma, ddof=1)


1.000

In [25]:
standard = (fish_data - mu)/sigma
standard

array([-1.732, -0.866, -0.866,  0.   ,  0.   ,  0.   ,  0.   ,  0.866,
        0.866,  1.732])

In [26]:
sp.mean(standard)

/var/folders/x4/rh_l0vln5g9bf9fqbtvsc7m80000gn/T/ipykernel_1666/1587171175.py:1: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  sp.mean(standard)


-0.000

In [28]:
sp.std(standard, ddof=1)

/var/folders/x4/rh_l0vln5g9bf9fqbtvsc7m80000gn/T/ipykernel_1666/882488789.py:1: DeprecationWarning: scipy.std is deprecated and will be removed in SciPy 2.0.0, use numpy.std instead
  sp.std(standard, ddof=1)


1.000

In [29]:
#그 외의 통계량
sp.amax(fish_data)

/var/folders/x4/rh_l0vln5g9bf9fqbtvsc7m80000gn/T/ipykernel_1666/754736962.py:2: DeprecationWarning: scipy.amax is deprecated and will be removed in SciPy 2.0.0, use numpy.amax instead
  sp.amax(fish_data)


6

In [30]:
sp.amin(fish_data)

/var/folders/x4/rh_l0vln5g9bf9fqbtvsc7m80000gn/T/ipykernel_1666/2453356564.py:1: DeprecationWarning: scipy.amin is deprecated and will be removed in SciPy 2.0.0, use numpy.amin instead
  sp.amin(fish_data)


2

In [31]:
sp.median(fish_data)

/var/folders/x4/rh_l0vln5g9bf9fqbtvsc7m80000gn/T/ipykernel_1666/3872521886.py:1: DeprecationWarning: scipy.median is deprecated and will be removed in SciPy 2.0.0, use numpy.median instead
  sp.median(fish_data)


4.000

In [32]:
fish_data_2 = np.array([2,3,3,4,4,4,4,5,5,100])

In [33]:
sp.mean(fish_data_2)

/var/folders/x4/rh_l0vln5g9bf9fqbtvsc7m80000gn/T/ipykernel_1666/2745575324.py:1: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  sp.mean(fish_data_2)


13.400

In [34]:
sp.median(fish_data_2)

/var/folders/x4/rh_l0vln5g9bf9fqbtvsc7m80000gn/T/ipykernel_1666/3051821626.py:1: DeprecationWarning: scipy.median is deprecated and will be removed in SciPy 2.0.0, use numpy.median instead
  sp.median(fish_data_2)


4.000

In [35]:
#scipy.stats와 사분위수
from scipy import stats

fish_data_3 = np.array([1,2,3,4,5,6,7,8,9])
stats.scoreatpercentile(fish_data_3, 25)

3.000

In [36]:
stats.scoreatpercentile(fish_data_3, 75)

7.000

In [39]:
#다변량 데이터 
#수치 계산에 사용하는 라이브러리 
import pandas as pd
import scipy as sp
#표시 자릿수 지정
%precision 3

'%.3f'

In [42]:
fish_df = pd.DataFrame({'Species':['A','A','A','B','B','B'], 'length':[2,3,4,6,8,10]})
fish_df

Species  length
0       A       2
1       A       3
2       A       4
3       B       6
4       B       8
5       B      10

In [45]:
group = fish_df.groupby("Species")
print(group.mean())

         length
Species        
A           3.0
B           8.0


In [48]:
print(group.std(ddof=1))

         length
Species        
A           1.0
B           2.0


In [49]:
group.describe()

length                                    
         count mean  std  min  25%  50%  75%   max
Species                                           
A          3.0  3.0  1.0  2.0  2.5  3.0  3.5   4.0
B          3.0  8.0  2.0  6.0  7.0  8.0  9.0  10.0

In [51]:
#교차분석표 구현하기 
shoes = pd.DataFrame({'store':['tokyo','tokyo','osaka','osaka'], 'color':['blue','red','blue','red'],'sales':[10,15,13,9]})
shoes

store color  sales
0  tokyo  blue     10
1  tokyo   red     15
2  osaka  blue     13
3  osaka   red      9

In [52]:
cross = pd.pivot_table(data=shoes, #데이터를 지정
                      values='sales', #데이터를 모을 열 지정
                      aggfunc='sum', #데이터를 모을 함수 지정
                      index='store', #교차분석표의 행 지정
                      columns='color' #교차분석표의 열 지정
                      ) 
print(cross)

color  blue  red
store           
osaka    13    9
tokyo    10   15


In [ ]:
#공분산